### ISSUE TITLE
pynml-plotmorph -interactive (vispy) seems broken with numpy 2.3.1

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/pyNeuroML#452]
It doesn't seem to work for me on py312 and py313 at least:

```
pynml-plotmorph -inter test.cell.nml
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
pyNeuroML >>> 14:33:50 - INFO - Loading NeuroML2 file: test.cell.nml
pyNeuroML >>> 14:33:50 - INFO - Processing 1 cells
/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib/python3.12/site-packages/OpenGL/platform/egl.py:76: ResourceWarning: unclosed file <_io.TextIOWrapper name='/proc/cpuinfo' mode='r' encoding='UTF-8'>
  info = open('/proc/cpuinfo').read()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
INFO:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib/python3.12/site-packages/jupyter_client/connect.py:22: DeprecationWarning: Jupyter is migrating its paths to use standard platformdirs
given by the platformdirs library.  To remove this warning and
see the appropriate new directories, set the environment variable
`JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
The use of platformdirs will be the default in `jupyter_core` v6
  from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
1 of 1|###############################################################################################################################################|Elapsed Time: 0:00:00
pyNeuroML >>> 14:33:50 - INFO - Processing 8 segments
8 of 8|###############################################################################################################################################|Elapsed Time: 0:00:00
WARNING: Error drawing visual <vispy.visuals.text.text.TextVisual object at 0x7f82653d21b0>
WARNING:vispy:Error drawing visual <vispy.visuals.text.text.TextVisual object at 0x7f82653d21b0>
WARNING: Traceback (most recent call last):
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/bin/pynml-plotmorph", line 8, in <module>
    sys.exit(main())
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib/python3.12/site-packages/pyneuroml/plot/PlotMorphology.py", line 170, in main
    plot_from_console(a=args)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib/python3.12/site-packages/pyneuroml/plot/PlotMorphology.py", line 185, in plot_from_console
    plot_interactive_3D(
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib/python3.12/site-packages/pyneuroml/plot/PlotMorphologyVispy.py", line 917, in plot_interactive_3D
    current_canvas.show()
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/app/canvas.py", line 435, in show
    self._backend._vispy_set_visible(visible)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/app/backends/_qt.py", line 465, in _vispy_set_visible
    self.showNormal()
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/app/backends/_qt.py", line 655, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/app/backends/_qt.py", line 655, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/app/backends/_qt.py", line 963, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/scene/canvas.py", line 219, in on_draw
    self._draw_scene()
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/scene/canvas.py", line 278, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/scene/canvas.py", line 316, in draw_visual
    node.draw()
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/scene/visuals.py", line 106, in draw
    self._visual_superclass.draw(self)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/visuals/visual.py", line 668, in draw
    v.draw()
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/visuals/visual.py", line 514, in draw
    self._program.draw(self._vshare.draw_mode,
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/visuals/shaders/program.py", line 102, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/gloo/program.py", line 543, in draw
    canvas.context.flush_commands()
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/gloo/context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/gloo/glir.py", line 584, in flush
    self._shared.flush(parser)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/gloo/glir.py", line 506, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/gloo/glir.py", line 824, in parse
    self._parse(command)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/gloo/glir.py", line 804, in _parse
    ob.link_program(*args)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/gloo/glir.py", line 1127, in link_program
    self._unset_variables = self._get_active_attributes_and_uniforms()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/gloo/glir.py", line 1148, in _get_active_attributes_and_uniforms
    name, size, gtype = func(self._handle, i)
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/gloo/gl/_pyopengl2.py", line 91, in glGetActiveAttrib
    return name.decode('utf-8'), size, type
           ^^^^^^^^^^^
AttributeError: 'numpy.ndarray' object has no attribute 'decode'
WARNING:vispy:Traceback (most recent call last):
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/bin/pynml-plotmorph", line 8, in <module>
    sys.exit(main())
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib/python3.12/site-packages/pyneuroml/plot/PlotMorphology.py", line 170, in main
    plot_from_console(a=args)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib/python3.12/site-packages/pyneuroml/plot/PlotMorphology.py", line 185, in plot_from_console
    plot_interactive_3D(
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib/python3.12/site-packages/pyneuroml/plot/PlotMorphologyVispy.py", line 917, in plot_interactive_3D
    current_canvas.show()
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/app/canvas.py", line 435, in show
    self._backend._vispy_set_visible(visible)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/app/backends/_qt.py", line 465, in _vispy_set_visible
    self.showNormal()
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/app/backends/_qt.py", line 655, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/app/backends/_qt.py", line 655, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/app/backends/_qt.py", line 963, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/scene/canvas.py", line 219, in on_draw
    self._draw_scene()
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/scene/canvas.py", line 278, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/scene/canvas.py", line 316, in draw_visual
    node.draw()
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/scene/visuals.py", line 106, in draw
    self._visual_superclass.draw(self)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/visuals/visual.py", line 668, in draw
    v.draw()
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/visuals/visual.py", line 514, in draw
    self._program.draw(self._vshare.draw_mode,
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/visuals/shaders/program.py", line 102, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/gloo/program.py", line 543, in draw
    canvas.context.flush_commands()
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/gloo/context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/gloo/glir.py", line 584, in flush
    self._shared.flush(parser)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/gloo/glir.py", line 506, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/gloo/glir.py", line 824, in parse
    self._parse(command)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/gloo/glir.py", line 804, in _parse
    ob.link_program(*args)
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/gloo/glir.py", line 1127, in link_program
    self._unset_variables = self._get_active_attributes_and_uniforms()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/gloo/glir.py", line 1148, in _get_active_attributes_and_uniforms
    name, size, gtype = func(self._handle, i)
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asinha/.local/share/virtualenvs/neuroml-dev-312/lib64/python3.12/site-packages/vispy/gloo/gl/_pyopengl2.py", line 91, in glGetActiveAttrib
    return name.decode('utf-8'), size, type
           ^^^^^^^^^^^
AttributeError: 'numpy.ndarray' object has no attribute 'decode'
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt6) at 0x7f827e133860>> for DrawEvent
ERROR:vispy:Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt6) at 0x7f827e133860>> for DrawEvent
WARNING: Error drawing visual <vispy.visuals.text.text.TextVisual object at 0x7f82653d21b0>
WARNING:vispy:Error drawing visual <vispy.visuals.text.text.TextVisual object at 0x7f82653d21b0>
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt6) at 0x7f827e133860>> repeat 2
ERROR:vispy:Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt6) at 0x7f827e133860>> repeat 2
WARNING: Error drawing visual <vispy.visuals.text.text.TextVisual object at 0x7f82653d21b0>
WARNING:vispy:Error drawing visual <vispy.visuals.text.text.TextVisual object at 0x7f82653d21b0>
```

I need to debug this further to see what's going on, but filing a ticket so it's on our radar.

```
pip list | grep -iE '(vispy|qt)'
PyQt6                     6.9.1
PyQt6-Qt6                 6.9.1
PyQt6_sip                 13.10.2
vispy                     0.15.2
```

**Comment by sanjayankur31** [comment]
Hrm, this works for me now. Not sure.

```
pip list | grep -iE '(vispy|qt|numpy)'
numpy                     2.2.6
PyQt6                     6.9.1
PyQt6-Qt6                 6.9.1
PyQt6_sip                 13.10.2
vispy                     0.15.2
```

The difference is in numpy: it doesn't work with numpy 2.3.1..

**Comment by sanjayankur31** [comment]
No, it's another case of it needing the `QT_QPA_PLATFORM=wayland-egl` variable. I wonder if we can detect wayland and set this automatically..

**Comment by sanjayankur31** [comment]
Reopening. Seeing this on Wayland with numpy 2.3.1, even after using the variable. 

I need to test out vispy examples to see if this is a vispy issue (should be, because we haven't really changed our code and it isn't numpy version dependent)

**Comment by sanjayankur31** [comment]
Filed: https://github.com/vispy/vispy/issues/2683
